# If you change this file, restart the server.

# Site settings
# {{ site.title }}, {{ site.email }}, etc.
# Custom variables will be accessible in the templates via {{ site.myvariable }}.
title: "Greg Smith"
description: "I kick ass."
lang: "en"
baseurl: "/"
url: "https://gregsmith.design" 

# DATA
team_members:
  -
    name: "Sarah Becker"
    role: "project lead"
    start: "2016-02-01"
  -
    name: "Jane Smith"
    role: "maintainer"
    start: "2018-03-15"
  -
    name: "Albert Hamilton"
    role: "editor"
    start: "2017-12-01"

# COLLECTIONS
collections:
  work:
    output: true
    permalink: /:collection/:title
    title: shiz
    description: shazzlesz

# Adding plugin for PurgeCSS
plugins:
  - jekyll-purgecss

css_dir: "_site/css" # defaults to "css"

# Default CSS path: /css/style.css
# css: inline
# Don't purge when working locally. No reason to.
# When prepping for production:
# 1. bundle exec jekyll build
# 2. purgecss --css _site/css/style.css --content _site/**/*.html --output _site/css/style.css
# 4. Commit, push, deploy

# Build settings
markdown: kramdown

kramdown:
  auto_ids: false

sass:
  style: compressed

# Defaults
# Enable is_homepost test for posts
# Enable is_page test for pages
# Enable is_home test for home page
# Use {% if page.is_post %} etc.

defaults:
-
    scope:
        path: "/" # empty string for all files
    values:
        is_home: true
-
    scope:
        path: ""
        type: posts
    values:
        is_post: true
-
    scope:
        path: ""
        type: pages
    values:
        is_page: true

# Exclude from processing.
# The following items will not be processed, by default.
# Create a custom list to override the default setting.

exclude:
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
